# Site settings
title: 数据路由
email: pickstone78@163.com
description: > 
  如何让数据在物联网上更自由的奔跑?
baseurl: "" 
url: "http://pickstone78.github.io" 
github_username:  PickStone78

# Build settings
markdown: kramdown
